### ISSUE TITLE
运行 test-time adaptation on DIV2K-MC 遇到问题

### ISSUE THREAD

**Issue by cuishuang99** [DengZeshuai/SRTTA#3]
在运行test-time adaptation(DIV2K-MC)时，发现此阶段的log显示的结果和您在GitHub上所放置有些许出入，主要是退化预测不一致。例如，退化类型为BlurJPEG时，分类器预测结果为GaussianNoise，导致自适应后的模型结果变差。因此，想请教您是否在测试时自适应中需要什么trick? 或者我根据GitHub 教程上的方法有什么问题和改进的地方？期待您的解答！

**Comment by cuishuang99** [comment]
log(https://github.com/DengZeshuai/SRTTA/assets/103561864/124e1b43-379a-48ee-b9af-f2183a46cabe)

**Comment by DengZeshuai** [comment]
我们今天发现了先前发布的代码在分类预测的时候有个地方弄错了，可以先基于最新的代码跑一次。 
我们这边也会确认一下是否为这个错误导致的问题。

**Comment by cuishuang99** [comment]
谢谢您的解答，应该是这个错误导致的问题。更新后的代码，TTA的结果跟论文基本一致
